require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

# Metrics/BlockLength:
#   Exclude:
#     - 'test/*.rb'

# TODO: When we drop support for ruby 2.4 and 2.5
# change YAML.load(f) in test/exiftool_test.rb
# to YAML.safe_load(f, permitted_classes: [Symbol, Date, Rational])
Security/YAMLLoad:
  Exclude:
    - 'test/exiftool_test.rb'

########
# Below exclusions would require major refactoring
# Ignoring for until better times...

Metrics/AbcSize:
  Max: 24

Metrics/MethodLength:
  Max: 17

Metrics/BlockLength:
  Max: 100